name: free5gc

services:
    # auto-verif:
    #     container_name: auto-verif
    #     build:
    #         context: ../
    #         dockerfile: Dockerfile
    #     privileged: true
    #     ports:
    #         - "8090:8090"
    #     command: go run .
    #     volumes:
    #         - /home/demo/AutoVerif/free5gc-compose/config:/app/src/pkg/config
    #         - /home/demo/AutoVerif/free5gc-compose/files:/app/src/pkg/files
    #     networks:
    #         ground:
    #             ipv4_address: 10.100.200.60

    core-dns:
        container_name: core-dns
        image: coredns/coredns:latest
        restart: on-failure # other option: always - if you want persistent through host reboots
        networks:
            util:
                ipv4_address: 10.102.200.50
            ground:
                ipv4_address: 10.100.200.50
            satellite:
                ipv4_address: 10.101.200.50
        # entrypoint: ["/bin/sh", "-c"]
        command: -conf /etc/coredns/Corefile
        volumes:
            - "./config/Corefile:/etc/coredns/Corefile"

    i-router:
        container_name: i-router
        build:
            context: ./router
            dockerfile: Dockerfile
        networks:
            util:
                ipv4_address: 10.102.200.40
            ground:
                ipv4_address: 10.100.200.40
            satellite:
                ipv4_address: 10.101.200.40
        entrypoint: ["/bin/sh", "-c"]
        privileged: true
        command:
            - |
                route add -net 10.100.200.0/24 gw 10.100.200.40
                route add -net 10.101.200.0/24 gw 10.101.200.40
                route add -net 10.102.200.0/24 gw 10.102.200.40
                route add -net 10.60.0.0/24 gw 10.101.200.40
                route add -net 10.61.0.0/24 gw 10.100.200.40
                tail -f /dev/null
        dns: 10.100.200.50

    iperf-server:
        container_name: iperf-server
        build:
            context: ./iperf3
            dockerfile: Dockerfile
        privileged: true
        ports:
            - "5001:5001"
        networks:
            util:
                ipv4_address: 10.102.200.30
                aliases:
                    - iperf-server.free5gc.org
        dns: 10.102.200.50
        entrypoint: /iperf3/config/entrypoint.sh
        stdin_open: true
        volumes:
            - ./iperf3/entrypoint.sh:/iperf3/config/entrypoint.sh
        tty: true

    free5gc-upf1:
        container_name: upf1
        build:
            context: ./nf_upf
            args:
                DEBUG_TOOLS: "true"
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
                route add -net 10.102.200.0/24 gw 10.101.200.40
                route add -net 10.100.200.0/24 gw 10.101.200.40
                bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
        volumes:
            - ./config/upfcfg1.yaml:/free5gc/config/upfcfg.yaml
            - ./config/upf-iptables.sh:/free5gc/upf-iptables.sh
        # deploy:
        #     resources:
        #         limits:
        #             cpus: "0.5"
        cap_add:
            - NET_ADMIN
        dns: 10.101.200.50
        networks:
            satellite:
                aliases:
                    - upf1.free5gc.org

    free5gc-upf2:
        container_name: upf2
        build:
            context: ./nf_upf
            args:
                DEBUG_TOOLS: "true"
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
                route add -net 10.102.200.0/24 gw 10.100.200.40
                bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
        volumes:
            - ./config/upfcfg2.yaml:/free5gc/config/upfcfg.yaml
            - ./config/upf-iptables.sh:/free5gc/upf-iptables.sh
        # deploy:
        #     resources:
        #         limits:
        #             cpus: "0.1"
        cap_add:
            - NET_ADMIN
        dns: 10.100.200.50
        networks:
            ground:
                aliases:
                    - upf2.free5gc.org

    db:
        container_name: mongodb
        image: mongo
        command: mongod --port 27017
        expose:
            - "27017"
        volumes:
            - dbdata:/data/db
        networks:
            ground:
                aliases:
                    - db

    free5gc-nrf:
        container_name: nrf
        build:
            context: ./nf_nrf
            args:
                DEBUG_TOOLS: "false"
        entrypoint: ["/bin/sh", "-c"]
        privileged: true
        dns: 10.100.200.50
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./nrf -c ./config/nrfcfg.yaml
        expose:
            - "8000"
        volumes:
            - ./config/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
            - ./cert:/free5gc/cert
        environment:
            DB_URI: mongodb://db/free5gc
            GIN_MODE: release
        networks:
            ground:
                aliases:
                    - nrf.free5gc.org
        depends_on:
            - db

    free5gc-amf:
        container_name: amf
        build:
            context: ./nf_amf
            args:
                DEBUG_TOOLS: "false"
        entrypoint: ["/bin/sh", "-c"]
        privileged: true
        dns: 10.100.200.50
        cap_add:
            - NET_ADMIN
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./amf -c ./config/amfcfg.yaml
        expose:
            - "8000"
        volumes:
            - ./config/amfcfg.yaml:/free5gc/config/amfcfg.yaml
            - ./cert:/free5gc/cert
        environment:
            GIN_MODE: release
        devices:
            - "/dev/net/tun"
        networks:
            ground:
                aliases:
                    - amf.free5gc.org
        depends_on:
            - free5gc-nrf

    free5gc-ausf:
        container_name: ausf
        build:
            context: ./nf_ausf
            args:
                DEBUG_TOOLS: "false"
        privileged: true
        entrypoint: ["/bin/sh", "-c"]
        dns: 10.100.200.50
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./ausf -c ./config/ausfcfg.yaml
        expose:
            - "8000"
        volumes:
            - ./config/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
            - ./cert:/free5gc/cert
        environment:
            GIN_MODE: release
        networks:
            ground:
                aliases:
                    - ausf.free5gc.org
        depends_on:
            - free5gc-nrf

    free5gc-nssf:
        container_name: nssf
        build:
            context: ./nf_nssf
            args:
                DEBUG_TOOLS: "false"
        privileged: true
        dns: 10.100.200.50
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./nssf -c ./config/nssfcfg.yaml
        expose:
            - "8000"
        volumes:
            - ./config/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
            - ./cert:/free5gc/cert
        environment:
            GIN_MODE: release
        networks:
            ground:
                aliases:
                    - nssf.free5gc.org
        depends_on:
            - free5gc-nrf

    free5gc-pcf:
        container_name: pcf
        build:
            context: ./nf_pcf
            args:
                DEBUG_TOOLS: "false"
        privileged: true
        dns: 10.100.200.50
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./pcf -c ./config/pcfcfg.yaml
        expose:
            - "8000"
        volumes:
            - ./config/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
            - ./cert:/free5gc/cert
        environment:
            GIN_MODE: release
        networks:
            ground:
                aliases:
                    - pcf.free5gc.org
        depends_on:
            - free5gc-nrf

    free5gc-smf:
        container_name: smf
        build:
            context: ./nf_smf
            args:
                DEBUG_TOOLS: "false"
        privileged: true
        dns: 10.100.200.50
        cap_add:
            - NET_ADMIN
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
        expose:
            - "8000"
        volumes:
            - ./config/smfcfg.yaml:/free5gc/config/smfcfg.yaml
            - ./config/uerouting.yaml:/free5gc/config/uerouting.yaml
            - ./cert:/free5gc/cert
        environment:
            GIN_MODE: release
        devices:
            - "/dev/net/tun"
        networks:
            ground:
                aliases:
                    - smf.free5gc.org
        depends_on:
            - free5gc-nrf
            - free5gc-upf1
            - free5gc-upf2

    free5gc-udm:
        container_name: udm
        build:
            context: ./nf_udm
            args:
                DEBUG_TOOLS: "false"
        privileged: true
        dns: 10.100.200.50
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./udm -c ./config/udmcfg.yaml
        expose:
            - "8000"
        volumes:
            - ./config/udmcfg.yaml:/free5gc/config/udmcfg.yaml
            - ./cert:/free5gc/cert
        environment:
            GIN_MODE: release
        networks:
            ground:
                aliases:
                    - udm.free5gc.org
        depends_on:
            - db
            - free5gc-nrf

    free5gc-udr:
        container_name: udr
        build:
            context: ./nf_udr
            args:
                DEBUG_TOOLS: "false"
        privileged: true
        dns: 10.100.200.50
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./udr -c ./config/udrcfg.yaml
        expose:
            - "8000"
        volumes:
            - ./config/udrcfg.yaml:/free5gc/config/udrcfg.yaml
            - ./cert:/free5gc/cert
        environment:
            DB_URI: mongodb://db/free5gc
            GIN_MODE: release
        networks:
            ground:
                aliases:
                    - udr.free5gc.org
        depends_on:
            - db
            - free5gc-nrf

    free5gc-chf:
        container_name: chf
        build:
            context: ./nf_chf
            args:
                DEBUG_TOOLS: "false"
        entrypoint: ["/bin/sh", "-c"]
        privileged: true
        dns: 10.100.200.50
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./chf -c ./config/chfcfg.yaml
        expose:
            - "8000"
            - "2122"
        volumes:
            - ./config/chfcfg.yaml:/free5gc/config/chfcfg.yaml
            - ./cert:/free5gc/cert
        environment:
            DB_URI: mongodb://db/free5gc
            GIN_MODE: release
        networks:
            ground:
                aliases:
                    - chf.free5gc.org
        depends_on:
            - db
            - free5gc-nrf
            - free5gc-webui

    free5gc-n3iwf:
        container_name: n3iwf
        build:
            context: ./nf_n3iwf
            args:
                DEBUG_TOOLS: "false"
        entrypoint: ["/bin/sh", "-c"]
        privileged: true
        dns: 10.100.200.50
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                sh -c "./n3iwf-ipsec.sh && ./n3iwf -c ./config/n3iwfcfg.yaml"
        volumes:
            - ./config/n3iwfcfg.yaml:/free5gc/config/n3iwfcfg.yaml
            - ./config/n3iwf-ipsec.sh:/free5gc/n3iwf-ipsec.sh
        environment:
            GIN_MODE: release
        cap_add:
            - NET_ADMIN
        networks:
            ground:
                ipv4_address: 10.100.200.15
                aliases:
                    - n3iwf.free5gc.org
        depends_on:
            - free5gc-amf
            - free5gc-smf
            - free5gc-upf1
            - free5gc-upf2

    free5gc-webui:
        container_name: webui
        build:
            context: ./webui
            args:
                DEBUG_TOOLS: "false"
        command: ./webui -c ./config/webuicfg.yaml
        dns: 10.100.200.50
        expose:
            - "2121"
        volumes:
            - ./config/webuicfg.yaml:/free5gc/config/webuicfg.yaml
        environment:
            - GIN_MODE=release
        networks:
            ground:
                aliases:
                    - webui
        ports:
            - "5000:5000"
        depends_on:
            - db
            - free5gc-nrf

    gnb1:
        container_name: gnb1
        build:
            context: ./ueransim
        entrypoint: ["/bin/sh", "-c"]
        dns: 10.101.200.50
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./nr-gnb -c ./config/gnbcfg.yaml
        volumes:
            - ./config/gnbcfg1.yaml:/ueransim/config/gnbcfg.yaml
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"
        networks:
            ground:
                aliases:
                    - gnb1.free5gc.org
        depends_on:
            - free5gc-amf
            - free5gc-upf1
            - free5gc-upf2
            - free5gc-n3iwf

    gnb2:
        container_name: gnb2
        build:
            context: ./ueransim
        dns: 10.100.200.50
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
                route add -net 10.101.200.0/24 gw 10.100.200.40
                ./nr-gnb -c ./config/gnbcfg.yaml
        volumes:
            - ./config/gnbcfg2.yaml:/ueransim/config/gnbcfg.yaml
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"
        networks:
            ground:
                aliases:
                    - gnb2.free5gc.org
        depends_on:
            - free5gc-amf
            - free5gc-upf1
            - free5gc-upf2
            - free5gc-n3iwf

    ueransim:
        container_name: ueransim
        build:
            context: ./ueransim
        entrypoint: /ueransim/config/entrypoint.sh
        dns: 10.100.200.50
        volumes:
            - ./config/ue/ue1.yaml:/ueransim/config/uecfg1.yaml
            # - ./config/ue/ue2.yaml:/ueransim/config/uecfg2.yaml
            # - ./config/ue/ue3.yaml:/ueransim/config/uecfg3.yaml
            - ./ueransim/entrypoint.sh:/ueransim/config/entrypoint.sh
            - ./logs/iperf-results:/ueransim/logs/iperf-results
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"
        networks:
            ground:
                aliases:
                    - ueransim.free5gc.org
        depends_on:
            - free5gc-amf
            - free5gc-upf1
            - free5gc-upf2
            - gnb1
            - gnb2

    n3iwue:
        container_name: n3iwue
        build:
            context: ./n3iwue
        command: sleep infinity
        dns: 10.100.200.50
        volumes:
            - ./config/n3uecfg.yaml:/n3iwue/config/n3ue.yaml
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"
        networks:
            ground:
                aliases:
                    - n3ue.free5gc.org
        depends_on:
            - free5gc-n3iwf

networks:
    ground:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.200.0/24
        driver_opts:
            com.docker.network.bridge.name: br-free5gc-gr
    satellite:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.101.200.0/24
        driver_opts:
            com.docker.network.bridge.name: br-free5gc-sat
    util:
        driver: bridge
        ipam:
            config:
                - subnet: 10.102.200.0/24

volumes:
    dbdata:
